name: shell-cmds

on: 
  workflow_dispatch:
  push:
    branches:
    - master
permissions:
      id-token: write
jobs:
  show_qa:
    environment: qa
    runs-on: ubuntu-latest
    steps:
    - run: echo  ${{ secrets.AWS_ROLE_TO_ASSUME }}
    
  show_prod:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - run: echo  ${{ secrets.AWS_ROLE_TO_ASSUME }}
    
  runss:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/hello-world-javascript-action@v1
      id: js 
      with:
        who-to-greet: raghav
    - run: echo "${{ steps.js.outputs.time }}"
    
    
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: MySessionName
