name: shell-cmds

on: 
  push:
    branches:
    - master

jobs:
  runs_shell_command:
    runs-on: self-hosted
    steps:
    - run: echo 'Hello Self s'
    - run: import this
      shell: python
  runss:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/hello-world-javascript-action@v1
      id: js 
      with:
        who-to-greet: raghav
    - run: echo "${{ steps.js.outputs.time }}"
