name: shell-cmds

on: 
  push:
    branches:
    - master

jobs:
  runs_shell_command:
    runs-on: self-hosted
    steps:
    - run: echo 'Hello Self hosted'
    - run: import this
      shell: python