name: test 

on:
  push:
  - master

jobs:
  show_variables:
    runs-on: ubuntu-latest
    steps:
    - run: |
        import os 
        print(os.env.get('github',None))
      shell: python
    - run: echo "${{ github }}"